column_guides {
    column_name_pattern: "^contains.*",
    type: NUMERICAL
}

column_guides {
    column_name_pattern: "type",
    type: CATEGORICAL
}

column_guides {
    column_name_pattern: "encoded_text",
    type: CATEGORICAL
}